"""Migration-chain integrity guard.

A migration that ``drop_table``s something a later head still needs is invisible to the
unit suite (which builds its schema from ``Base.metadata.create_all``, not from the
migrations). That is exactly how ``reports`` and ``question_templates`` went missing on
fresh deploys: an autogenerated migration dropped them because the models were absent from
``Base.metadata`` at generation time.

This test statically walks the migration chain from base to head, simulating each
``upgrade()``'s ``create_table`` / ``drop_table`` operations, and asserts that every table
registered on ``Base.metadata`` exists at head. It needs no database, so it runs everywhere
CI does and fails loudly the moment a model table would be created-then-dropped (or never
created) by the chain.
"""

from __future__ import annotations

import re
from pathlib import Path

import app.models  # noqa: F401  (registers every model on Base.metadata)
from app.db.base import Base

_VERSIONS = Path(__file__).resolve().parent.parent / "alembic" / "versions"
_CREATE = re.compile(r"op\.create_table\(\s*['\"](\w+)['\"]")
_DROP = re.compile(r"op\.drop_table\(\s*['\"](\w+)['\"]")
_REVISION = re.compile(r"^revision\s*=\s*['\"]([^'\"]+)['\"]", re.MULTILINE)
_DOWN = re.compile(r"^down_revision\s*=\s*(?:['\"]([^'\"]+)['\"]|None)", re.MULTILINE)


def _load_migrations() -> dict[str, dict]:
    out: dict[str, dict] = {}
    for path in _VERSIONS.glob("*.py"):
        src = path.read_text()
        rev_m = _REVISION.search(src)
        if not rev_m:
            continue
        down_m = _DOWN.search(src)
        down = down_m.group(1) if down_m else None
        # Only the upgrade() body — downgrade() routinely recreates tables it drops.
        upgrade_src = src.split("def downgrade", 1)[0]
        out[rev_m.group(1)] = {
            "down": down,
            "creates": _CREATE.findall(upgrade_src),
            "drops": _DROP.findall(upgrade_src),
        }
    return out


def _ordered_revisions(migrations: dict[str, dict]) -> list[str]:
    """Return revisions base -> head, asserting a single linear chain."""
    children = {rev: [] for rev in migrations}
    heads = []
    for rev, meta in migrations.items():
        down = meta["down"]
        if down is None:
            base = rev
        else:
            assert down in migrations, f"{rev} points at unknown down_revision {down}"
            children[down].append(rev)
    # Single head: exactly one revision is nobody's down_revision.
    referenced = {m["down"] for m in migrations.values() if m["down"]}
    heads = [rev for rev in migrations if rev not in referenced]
    assert len(heads) == 1, f"expected a single head, found {heads}"

    order: list[str] = []
    cur = base
    while cur is not None:
        order.append(cur)
        kids = children[cur]
        assert len(kids) <= 1, f"branch in migration chain at {cur}: {kids}"
        cur = kids[0] if kids else None
    assert len(order) == len(migrations), "migration chain is not fully linear/connected"
    return order


def test_every_model_table_survives_to_head():
    migrations = _load_migrations()
    order = _ordered_revisions(migrations)

    tables: set[str] = set()
    for rev in order:
        meta = migrations[rev]
        for name in meta["creates"]:
            tables.add(name)
        for name in meta["drops"]:
            tables.discard(name)

    expected = set(Base.metadata.tables.keys())
    missing = expected - tables
    assert not missing, (
        f"tables present in Base.metadata but absent at migration head: {sorted(missing)} "
        "— a migration likely drops a table it (or an earlier migration) created."
    )
