"""add form_audit_logs

Revision ID: 57c4197d45ea
Revises: r3s4t5u6v7w8
Create Date: 2026-06-18 13:24:17.872801
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '57c4197d45ea'
down_revision = 'r3s4t5u6v7w8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_audit_logs',
    sa.Column('form_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_audit_logs_form_id'), 'form_audit_logs', ['form_id'], unique=False)
    op.drop_index(op.f('ix_reports_form_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_question_templates_owner_id'), table_name='question_templates')
    op.drop_table('question_templates')
    op.add_column('webhook_deliveries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_deliveries', 'updated_at')
    op.create_table('question_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('element', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('question_templates_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('question_templates_pkey'))
    )
    op.create_index(op.f('ix_question_templates_owner_id'), 'question_templates', ['owner_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('form_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), server_default=sa.text("'Untitled Report'::character varying"), autoincrement=False, nullable=False),
    sa.Column('widgets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('reports_form_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    op.create_index(op.f('ix_reports_form_id'), 'reports', ['form_id'], unique=False)
    op.drop_index(op.f('ix_form_audit_logs_form_id'), table_name='form_audit_logs')
    op.drop_table('form_audit_logs')
    # ### end Alembic commands ###
