"""add form_audit_logs

Revision ID: 57c4197d45ea
Revises: r3s4t5u6v7w8
Create Date: 2026-06-18 13:24:17.872801
"""
from alembic import op
import sqlalchemy as sa

revision = '57c4197d45ea'
down_revision = 'r3s4t5u6v7w8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # This migration owns ``form_audit_logs`` and the ``webhook_deliveries.updated_at``
    # column only. An earlier autogenerated version also carried ``drop_table`` calls for
    # ``reports`` and ``question_templates`` — an autogenerate artifact from running against
    # a database whose model metadata was momentarily missing those tables. Those drops
    # silently removed tables that the ``r3s4t5u6v7w8`` and ``g7h8i9j0k1l2`` migrations had
    # just created, so a clean ``upgrade head`` ended up without them. They are deliberately
    # gone now; each table is managed solely by its own migration.
    conn = op.get_bind()
    if not conn.dialect.has_table(conn, 'form_audit_logs'):
        op.create_table(
            'form_audit_logs',
            sa.Column('form_id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=True),
            sa.Column('action', sa.String(length=50), nullable=False),
            sa.Column('summary', sa.Text(), nullable=True),
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(op.f('ix_form_audit_logs_form_id'), 'form_audit_logs', ['form_id'], unique=False)
    op.execute(
        "ALTER TABLE webhook_deliveries ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now()"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE webhook_deliveries DROP COLUMN IF EXISTS updated_at")
    op.drop_index(op.f('ix_form_audit_logs_form_id'), table_name='form_audit_logs')
    op.drop_table('form_audit_logs')
